<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\webform\Utility\WebformFormHelper;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function portal_form_webform_submission_book_class_form_alter(array &$form, FormStateInterface $form_state, $form_id) {
  $nid = \Drupal::routeMatch()->getRawParameter('node');
  if(!empty($nid)) {
    $elements = &WebformFormHelper::flattenElements($form['elements']);
    dpm($elements['class'], '$element');
    $elements['class']['#default_value'] = $nid;
  }
}